/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as RobotRouteImport } from './routes/robot'
import { Route as SponsorshipsRouteImport } from './routes/sponsorships'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotRoute = RobotRouteImport.update({
  id: '/robot',
  path: '/robot',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorshipsRoute = SponsorshipsRouteImport.update({
  id: '/sponsorships',
  path: '/sponsorships',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/outreach': typeof OutreachRoute
  '/programs': typeof ProgramsRoute
  '/robot': typeof RobotRoute
  '/sponsorships': typeof SponsorshipsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/outreach': typeof OutreachRoute
  '/programs': typeof ProgramsRoute
  '/robot': typeof RobotRoute
  '/sponsorships': typeof SponsorshipsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/outreach': typeof OutreachRoute
  '/programs': typeof ProgramsRoute
  '/robot': typeof RobotRoute
  '/sponsorships': typeof SponsorshipsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/about' | '/outreach' | '/programs' | '/robot' | '/sponsorships'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/outreach' | '/programs' | '/robot' | '/sponsorships'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/outreach'
    | '/programs'
    | '/robot'
    | '/sponsorships'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  OutreachRoute: typeof OutreachRoute
  ProgramsRoute: typeof ProgramsRoute
  RobotRoute: typeof RobotRoute
  SponsorshipsRoute: typeof SponsorshipsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robot': {
      id: '/robot'
      path: '/robot'
      fullPath: '/robot'
      preLoaderRoute: typeof RobotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsorships': {
      id: '/sponsorships'
      path: '/sponsorships'
      fullPath: '/sponsorships'
      preLoaderRoute: typeof SponsorshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  OutreachRoute: OutreachRoute,
  ProgramsRoute: ProgramsRoute,
  RobotRoute: RobotRoute,
  SponsorshipsRoute: SponsorshipsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
